GCP docs
logzio/documentation pull request #316
Opened 2023-12-06 22:59 UTC by nico-shishkin

2023-12-10 14:50 UTC, mirii1994 requested changes

2023-12-10 14:50 UTC, mirii1994 commented on docs/_include/general-shipping/gcp.md
> +
Can we specify in the file's name that this doc is for metrics?

2023-12-10 14:50 UTC, mirii1994 commented on docs/shipping/GCP/gcp-ai-platform.md
> +{@include: ../../_include/general-shipping/gcp.md}
How can we both add the include, and also add the specific value for telemetry_list that will allow shipping metrics for this specific service?
This comment applies to all the documents in this PR.

2024-01-08 21:12 UTC, nico-shishkin commented
Hi @mirii1994 , I've resolved the comments, I believe

2024-01-31 12:00 UTC, mirii1994 commented
@nico-shishkin I'm closing this PR because there's an issue with the Netlify preview, i'll open a new one instead.

2024-01-31 12:00 UTC, closed without merging