new aws lambda extension for go
logzio/documentation pull request #461
Opened 2024-03-25 07:45 UTC by bardabun

Introduced a Go integration for AWS Lambda with fresh layers.

This new file closely mirrors the pre-existing `aws-lambda-extension-node`, which has also been updated to modify commands and eliminate regional distinctions, ensuring a consistent layer version across all regions.

2024-03-25 07:59 UTC, yotamloe requested changes
Nice job! Since as for now we dont provide an instrumentation layer, can you include an example for a go lambda function with manual instrumentation as part of this doc? Also possible to point to relevant otel go instrumentation docs

2024-03-25 07:59 UTC, yotamloe commented on docs/shipping/AWS/aws-lambda-extension-go.md
> +id: Lambda-extension-node
`node` -> `go`

2024-03-25 07:59 UTC, yotamloe commented on docs/shipping/AWS/aws-lambda-extension-go.md
> +* A Lambda function with a Node.js or Go application that is not yet instrumented.
`node` -> `go`

2024-03-25 07:59 UTC, yotamloe commented on docs/shipping/AWS/aws-lambda-extension-go.md
> +Replace `<<YOUR-LAMBDA_FUNCTION_NAME>>` with the name of your Lambda function running the Node.js application.
`node` -> `go`

2024-03-25 07:59 UTC, yotamloe commented on docs/shipping/AWS/aws-lambda-extension-go.md
> +Replace `<<YOUR-LAMBDA_FUNCTION_NAME>>` with the name of your Lambda function running the Node.js application.
`node` -> `go`

2024-03-25 07:59 UTC, yotamloe commented on docs/shipping/AWS/aws-lambda-extension-go.md
> +Replace `<<YOUR-LAMBDA_FUNCTION_NAME>>` with the name of your Lambda function running the Node.js application.
`node` -> `go`

2024-03-25 08:25 UTC, yotamloe approved these changes
LGTM

2024-03-27 15:38 UTC, nico-shishkin commented
Looks good, let's merge

2024-03-28 07:51 UTC, merged